from rsf.proj import *

####################################################################
n1=81
n2=181
n3=181
h1=0.05 #km
h2=0.05
h3=0.05
Flow('wave1',None,
	'''
	echo in=wave1.bin n1=%d n2=%d n3=%d data_format=binary_float |
	sfdd form=native | 
	sfput d1=%g d2=%g d3=%g o1=0 o2=0 o3=0
	label1=Z label2=X label3=Y unit1=km unit2=km unit3=km
	'''%(n1,n2,n3,h1,h2,h3))
Flow('wave2',None,
	'''
	echo in=wave2.bin n1=%d n2=%d n3=%d data_format=binary_float |
	sfdd form=native | 
	sfput d1=%g d2=%g d3=%g o1=0 o2=0 o3=0
	label1=Z label2=X label3=Y unit1=km unit2=km unit3=km
	'''%(n1,n2,n3,h1,h2,h3))

iz=n1/2
ix=n2/2
iy=n3/2
Plot('wave1',
       '''
       byte allpos=n gainpanel=all |
       grey3 flat=n frame1=%d frame2=%d frame3=%d color=j title="(a) forward" 
       '''%(iz,ix,iy))
Plot('wave2',
       '''
       byte allpos=n gainpanel=all |
       grey3 flat=n frame1=%d frame2=%d frame3=%d color=j title="(b) reconstructed" 
       '''%(iz,ix,iy))
Result('cmp', 'wave1 wave2', 'TwoColumns')
End()
